export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const BROWSE_UNLOCK_USERS = "BROWSE_UNLOCK_USERS";
export const SET_MY_PROFILE = "SET_MY_PROFILE";
export const SET_PROFILE_USER = "SET_PROFILE_USER";

export const BROWSE_PRODUCTS = "BROWSE_PRODUCTS";
export const SET_CURRENT_PRODUCT  = "SET_CURRENT_PRODUCT";

export const SET_INSURANCES  = "SET_INSURANCES";
export const SET_INSURANCE_INFO  = "SET_INSURANCE_INFO";
export const SET_INSURANCE_PRICE  = "SET_INSURANCE_PRICE";
export const SET_CHECKOUT_URL = "SET_CHECKOUT_URL";
export const SET_BOUGHT_INSURANCE = "SET_BOUGHT_INSURANCE";

