export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const BROWSE_UNLOCK_USERS = "BROWSE_UNLOCK_USERS";
export const SET_MY_PROFILE = "SET_MY_PROFILE";
export const SET_PROFILE_USER = "SET_PROFILE_USER";

