# -*- coding: utf-8 -*-
"""rapydcare_underwriting_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14osVtgw_WstrP6710uHX2yG_ZpOrOcVK
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import sklearn as sklearn
import matplotlib.pyplot as plt

import pickle as pickle
import csv as csv

riskfactor_file = '/content/drive/My Drive/Colab Notebooks/data_1/underwritingriskfactor.csv'
riskfactor_data = pd.read_csv(riskfactor_file, sep=',')

riskfactor_data.head()

riskfactor_data.describe()



from sklearn.ensemble import RandomForestRegressor 
regressor = RandomForestRegressor(n_estimators = 100
                                  , random_state = 34)

from sklearn.model_selection import train_test_split

y = riskfactor_data['risk_factor'].values

X = riskfactor_data[['age_class', 'overweight','ped','ped2','smoking', 'alcoholic', 'undergoneProcedure']].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

regressor.fit(X_train, y_train)

y_output = regressor.predict(X_test)

plt.plot(y_output, 'r-', label='predicted')
plt.plot(y_test, 'o', label='actuals')
plt.legend(loc='best')
plt.show()

regressor.predict([[55, 0,0,0,0,0,0]])

regressor.predict([[25, 0,0,0,0,0,0]])

regressor.predict([[65, 0,0,0,0,0,0]])

regressor.predict([[65, 0,1,1,0,0,1]])

regressor.predict([[65, 1,1,1,1,1,0]])

regressor.predict([[35, 1,1,1,1,1,0]])

regressor.predict([[20, 1,1,1,1,1,0]])

regressor.predict([[65, 0,1,1,0,0,0]])

regressor.predict([[63, 0,1,1,0,0,0]])

regressor.predict([[60, 0,1,1,0,0,0]])

regressor.predict([[60, 0,0,1,0,0,0]])

filename = '/content/drive/My Drive/Colab Notebooks/data_1/underwritingModel.sav'
pickle.dump(regressor, open(filename, 'wb'))

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

