module.exports = {
    userType_individual : "individual",
    userType_business : "business",
    userType_partnerdoctor : "partnerdoctor",
    idCounter_users: "users",
    idCounter_products: "products",
    idCounter_businesses: "businesses",
    idCounter_claims: "claims",
    idCounter_documents: "documents",
    idCounter_insuranceorders: "insuranceorders",
    idCounter_insuranceproducts: "insuranceproducts",
    idCounter_nominees: "nominees",
    idCounter_policyinfos: "policyinfos",
    scenario_unlockUsers: 'unlockUsers',
    scenario_browseProducts: 'browseProducts',
    scenario_getUserInsurances: 'getUserInsurances',
};